name: Hydrolagen
favicon: null
layout_spectrum: 0.37675685272552073
typography_spectrum: 0.9291840526275337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.29044479387812316
  lightness: 0.8129446737002581
  saturation: 0.4332724695559591
  rhythmicContrast: 0.8664199367631227
purpose: []
